### PR TITLE
Bump the latest Python version used in tests to 3.11

### PR DESCRIPTION
**Pull request by mdumandag**

### CODE REVIEW

**Review by srknzl — APPROVED** [review]

**Comment by msr1132** [comment]
we are facing this issue in python 3.11
from hazelcast.config import ClientProperties
ImportError: cannot import name 'ClientProperties' from 'hazelcast.config' (/usr/lib/python3.11/site-packages/hazelcast/config.py)

**Comment by mdumandag** [comment]
@msr1132 which client version are you using? If it is from the 3.x series, we stopped developing it quite some time ago

**Comment by msr1132** [comment]
hazelcast-python-client==5.3.0
Python 3.11.3

**Comment by mdumandag** [comment]
@msr1132 There is no ClientProperties class in the 5.3.0 or any 4.x or 5.x versions. Are you sure that you are not on client version 3.12?

**Comment by msr1132** [comment]
we are using 3.x release. what is the fix for 3.x release.

**Pull request merged**
