### PR TITLE
python 3 support changes

### LINKED ISSUE #29: Python 3.x support
I'm trying to access an Hazelcast map through a python client. I'm trying to execute file [https://github.com/hazelcast/hazelcast-python-client/blob/master/examples/main.py](url)

I get the following error: `ImportError: No module named 'Queue'`

I'm running python 3.5.2. It seems that the python client is not made for python 3 .....

### PR DESCRIPTION
**Pull request by mdumandag**
fixes #29

### CODE REVIEW

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by mdumandag** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by waseem18** [comment]
Good work @mdumandag

**Pull request merged**
