### PR TITLE
Python 2 & 3 compatibility [WIP PR - Do not merge]

### PR DESCRIPTION
**Pull request by waseem18**
Hi folks,

This PR relates to the issue https://github.com/hazelcast/hazelcast-python-client/issues/29 - Making Hazelcast Python client Python 2 and 3 compatible.

I made lot of changes to make the client compatible with both Python 2 and 3 but got stuck at a point.

The current version of the client uses `asyncore` which because of which it's really tedious to make the code compatible with both Python 2 and 3.

I tried porting `asyncore` to `asyncio` but in vain.

I feel it's time we can move on to Python 3 (may be on a different branch named `dev`?)

I put up this PR so that any one who's interested can hop on it and try the `asyncore` - `asyncio` - `py `2-3` stuff.

### CODE REVIEW

**Comment by waseem18** [comment]
Kindly do not merge this PR - it's incomplete.

**Comment by asimarslan** [comment]
Hi @waseem18 ,
I think you are just tried to make things work for python3 in this PR. But we should also consider how it works in python 2.
For example `xrange` is removed in python 3. converting `xrange` to `range` does not solve the problem as it will poorly perform in python 2.

There is a nice library for this problem (or you can search for an alternative if you like).  You can check it.

http://six.readthedocs.io/
https://github.com/benjaminp/six

Cassandra python driver is python 2 & 3 compatible. So you can also look at their code for how they solved the compatibility problems. 
https://github.com/datastax/python-driver/

Thanks

**Comment by waseem18** [comment]
Thanks for the information @asimarslan 

I'll look into it :)

**Comment by dbrimley** [comment]
@waseem18 Did you get a chance to look at @asimarslan recommendations on https://github.com/hazelcast/hazelcast-python-client/pull/72#issuecomment-354300288

**Comment by waseem18** [comment]
@dbrimley Sorry, I missed this notification. I looked at @asimarslan 's comments and found then useful. As this PR is enormous and need lot of changes I'm gonna close this PR and comment at #73 

Thanks

**Pull request closed without merging**
