### PR TITLE
Useful method for custom serializer

### PR DESCRIPTION
**Pull request by mmsolutions**
This method let create proper buffer size in serializer.
I'm using javaobj-py3 package for Java object unmarshalling.

### CODE REVIEW

**Comment by asimarslan** [comment]
Hi @mmsolutions
Thanks for the fix. 
Can you visit the [Contributor Agreement](https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement). 
Can you please fill in the form and send us so that I can merge your PR.

**Comment by mmsolutions** [comment]
Of course. I have exposed position and size methods on API level.

**Comment by mmsolutions** [comment]
Hi, ICLA accepted. Are those chnages ok for merge?

**Comment by asimarslan** [comment]
verify

**Pull request merged**
