### PR TITLE
Issue #112: return non-None values

### PR DESCRIPTION
**Pull request by aalba6675**
Now 3-read_from_a_map.py works:

```
>>> import hazelcast
>>> import logging
>>> logging.basicConfig()
>>> logging.getLogger().setLevel(logging.INFO)
>>> config = hazelcast.ClientConfig()
>>> config.network_config.addresses.append("10.88.0.25:5701")
>>> config.network_config.addresses.append("10.88.0.26:5701")
>>> config.network_config.addresses.append("10.88.0.27:5701")
>>> config.group_config.name= 'production'
>>> client = hazelcast.HazelcastClient(config)
INFO:ClusterService:Connecting to Address(host=10.88.0.27, port=5701)
INFO:ConnectionManager:Authenticated with <hazelcast.reactor.AsyncoreConnection connected 10.88.0.27:5701 at 0x7f7000992c18>
INFO:ClusterService:New member list:

Members [3] {
	Member [10.88.0.26]:5701 - 47f8c80b-4751-437b-8c08-7953f21615ee
	Member [10.88.0.25]:5701 - 9d9fc330-c158-4ee0-9001-38d7cec1dd84
	Member [10.88.0.27]:5701 - c5434f06-27ee-4b83-8916-3a6b0665a4d9
}

INFO:HazelcastClient:Client started.
>>> 
>>> greetings_map = client.get_map("greetings-map")
INFO:ConnectionManager:Authenticated with <hazelcast.reactor.AsyncoreConnection connected 10.88.0.25:5701 at 0x7f6fee2a3710>
>>> list( greetings_map.key_set().result() )
INFO:ConnectionManager:Authenticated with <hazelcast.reactor.AsyncoreConnection connected 10.88.0.26:5701 at 0x7f6fee2af518>
['French', 'Spanish', 'German', 'Italian', 'English']
```

### CODE REVIEW

**Comment by mdumandag** [comment]
Thanks for the pr @aalba6675 
Let's start the tests and merge this change afterwards.

**Comment by sancar** [comment]
verify

**Comment by sancar** [comment]
Hi @aalba6675 , 
Can you add some unittests to prd to verify the fix ?

**Comment by sancar** [comment]
Hi @aalba6675 , for us to merge your pr, we need you to sign our contribution agreement. 
Can you sign our contribution agreement form and email back to: cla@hazelcast.com

[Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)

**Comment by aalba6675** [comment]
@sancar added unit test to `predicate_test.py` since that uses `key_set()` the most.

**Comment by aalba6675** [comment]
CLA done; please check with jaromir@hazelcast.com. Cheers!

**Comment by sancar** [comment]
verify

**Comment by sancar** [comment]
verify

**Pull request merged**
